[phases.setup]
nixPkgs = ["dotnet-sdk_6"]

[phases.install]
cmds = ["dotnet restore backend/SalesSupportBackend/SalesSupportBackend/SalesSupportBackend.csproj"]

[phases.build]
cmds = ["dotnet publish backend/SalesSupportBackend/SalesSupportBackend/SalesSupportBackend.csproj -c Release -o out"]

[start]
cmd = "dotnet out/SalesSupportBackend.dll"
